# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='资源id')),
                ('title', models.CharField(max_length=50, verbose_name='资源标题')),
                ('type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('link', models.TextField(blank=True, null=True, verbose_name='资源链接')),
                ('creater', models.TextField(max_length=50, verbose_name='创建者')),
                ('craetion_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
        ),
    ]
