# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0003_duchengproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('num', models.TextField(blank=True, null=True, verbose_name='序号')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.TextField(max_length=50, verbose_name='资源标题')),
                ('link', models.TextField(blank=True, null=True, verbose_name='资源链接')),
                ('creation_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('courser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.ClassName', verbose_name='所属课程')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resource_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='资源类型')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '资源类型',
                'verbose_name_plural': '资源类型',
                'db_table': 'type_name',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='周次数')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '周次数',
                'verbose_name_plural': '周次数',
                'db_table': 'week_name',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooc.Type', verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='resource',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooc.Week', verbose_name='周次数'),
        ),
    ]
