# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.TextField(max_length=50, verbose_name='资源标题'),
        ),
    ]
