# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-11 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0002_auto_20180328_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='craetion_time',
            new_name='creation_time',
        ),
    ]
