# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-16 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0006_classname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
