# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0010_delete_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
