# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-16 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171018_2154'),
        ('mooc', '0011_auto_20180416_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='classname',
            field=models.ForeignKey(default=datetime.datetime(2018, 4, 16, 21, 24, 0, 952199), on_delete=django.db.models.deletion.CASCADE, to='judge.ClassName', verbose_name='所属课程'),
            preserve_default=False,
        ),
    ]
