# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0013_remove_resource_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='week',
            field=models.CharField(max_length=50, null=True, verbose_name='所属课程'),
        ),
    ]
