# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0014_resource_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='周次数')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '周次数',
                'verbose_name_plural': '周次数',
                'db_table': 'week_num',
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='week',
            field=models.CharField(max_length=50, null=True, verbose_name='所属周次'),
        ),
    ]
