# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171018_2154'),
        ('mooc', '0015_auto_20180417_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='week',
        ),
        migrations.AddField(
            model_name='resource',
            name='classname',
            field=models.ManyToManyField(null=True, to='judge.ClassName', verbose_name='所属课程'),
        ),
        migrations.AlterModelTable(
            name='week',
            table='week_name',
        ),
    ]
