# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0016_auto_20180417_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='classname',
            field=models.ManyToManyField(to='judge.ClassName', verbose_name='所属课程'),
        ),
    ]
