# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171018_2154'),
        ('mooc', '0018_resource_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='classname',
        ),
        migrations.AddField(
            model_name='resource',
            name='courser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ClassName', verbose_name='所属课程'),
        ),
    ]
