# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0019_auto_20180418_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='courser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.ClassName', verbose_name='所属课程'),
        ),
    ]
