# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0020_auto_20180418_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='courser',
            new_name='courser_id',
        ),
    ]
