# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0029_auto_20180419_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='资源类型')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'type_name',
                'verbose_name': '资源类型',
                'verbose_name_plural': '资源类型',
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooc.Type', verbose_name='资源类型'),
        ),
    ]
