# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-22 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0030_auto_20180421_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
