# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-19 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0002_auto_20171018_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuchengProblem',
            fields=[
                ('ducheng_id', models.AutoField(primary_key=True, serialize=False, verbose_name='读程题id')),
                ('title', models.TextField(max_length=200)),
                ('program', models.TextField(blank=True, null=True, verbose_name='程序代码')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='正确结果')),
                ('in_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间')),
                ('classname', models.ManyToManyField(to='judge.ClassName', verbose_name='所属课程')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knowledgePoint1', models.ManyToManyField(to='judge.KnowledgePoint1', verbose_name='一级知识点')),
                ('knowledgePoint2', models.ManyToManyField(to='judge.KnowledgePoint2', verbose_name='二级知识点')),
            ],
            options={
                'verbose_name': '读程题',
                'verbose_name_plural': '读程题',
                'ordering': ['ducheng_id'],
            },
        ),
    ]
