# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20161027_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepoint1',
            name='name',
            field=models.CharField(max_length=50, verbose_name='一级知识点名称'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint2',
            name='name',
            field=models.CharField(max_length=50, verbose_name='二级知识点名称'),
        ),
    ]
