# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20170223_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='judger',
            field=models.CharField(default='LOCAL', max_length=16),
        ),
    ]
