# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_solution_judger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceproblem',
            name='a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choiceproblem',
            name='b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choiceproblem',
            name='c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choiceproblem',
            name='d',
            field=models.CharField(max_length=200),
        ),
    ]
