# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20170313_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='题目id'),
        ),
    ]
