# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-16 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0006_auto_20170516_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaicuoProblem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='题目id')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('input', models.TextField(blank=True, null=True, verbose_name='输入描述')),
                ('output', models.TextField(blank=True, null=True, verbose_name='输出描述')),
                ('program', models.TextField(blank=True, null=True, verbose_name='程序代码')),
                ('sample_input', models.TextField(blank=True, null=True, verbose_name='样例输入1')),
                ('sample_output', models.TextField(blank=True, null=True, verbose_name='样例输出1')),
                ('sample_input2', models.TextField(blank=True, null=True, verbose_name='样例输入2')),
                ('sample_output2', models.TextField(blank=True, null=True, verbose_name='样例输出2')),
                ('spj', models.CharField(default=0, max_length=1)),
                ('hint', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('in_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间')),
                ('time_limit', models.IntegerField(default=1, verbose_name='限制时间')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='限制内存')),
                ('defunct', models.CharField(default='N', max_length=1)),
                ('accepted', models.IntegerField(blank=True, default=0, null=True, verbose_name='AC数量')),
                ('submit', models.IntegerField(blank=True, default=0, null=True, verbose_name='提交数量')),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('classname', models.ManyToManyField(to='judge.ClassName', verbose_name='所属课程')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knowledgePoint1', models.ManyToManyField(to='judge.KnowledgePoint1', verbose_name='一级知识点')),
                ('knowledgePoint2', models.ManyToManyField(to='judge.KnowledgePoint2', verbose_name='二级知识点')),
            ],
            options={
                'verbose_name_plural': '程序改错题',
                'db_table': 'gaicuoproblem',
                'verbose_name': '程序改错题',
                'ordering': ['problem_id'],
            },
        ),
        migrations.CreateModel(
            name='TiankongProblem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='题目id')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('input', models.TextField(blank=True, null=True, verbose_name='输入描述')),
                ('output', models.TextField(blank=True, null=True, verbose_name='输出描述')),
                ('program', models.TextField(blank=True, null=True, verbose_name='程序代码')),
                ('sample_input', models.TextField(blank=True, null=True, verbose_name='样例输入1')),
                ('sample_output', models.TextField(blank=True, null=True, verbose_name='样例输出1')),
                ('sample_input2', models.TextField(blank=True, null=True, verbose_name='样例输入2')),
                ('sample_output2', models.TextField(blank=True, null=True, verbose_name='样例输出2')),
                ('spj', models.CharField(default=0, max_length=1)),
                ('hint', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('in_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间')),
                ('time_limit', models.IntegerField(default=1, verbose_name='限制时间')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='限制内存')),
                ('defunct', models.CharField(default='N', max_length=1)),
                ('accepted', models.IntegerField(blank=True, default=0, null=True, verbose_name='AC数量')),
                ('submit', models.IntegerField(blank=True, default=0, null=True, verbose_name='提交数量')),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('classname', models.ManyToManyField(to='judge.ClassName', verbose_name='所属课程')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knowledgePoint1', models.ManyToManyField(to='judge.KnowledgePoint1', verbose_name='一级知识点')),
                ('knowledgePoint2', models.ManyToManyField(to='judge.KnowledgePoint2', verbose_name='二级知识点')),
            ],
            options={
                'verbose_name_plural': '程序填空题',
                'db_table': 'tiankongproblem',
                'verbose_name': '程序填空题',
                'ordering': ['problem_id'],
            },
        ),
    ]
