# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20170818_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='program',
            field=models.TextField(blank=True, null=True, verbose_name='程序代码'),
        ),
    ]
