# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_problem_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='课程名称')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'class_name',
                'verbose_name': '课程名称',
                'verbose_name_plural': '课程名称',
            },
        ),
    ]
