# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-14 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20170914_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='class_name',
        ),
    ]
