# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-14 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20170914_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
