# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(null=True)),
                ('tid', models.CharField(max_length=40)),
            ],
        ),
    ]
