# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-05 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhomework',
            name='gaicuo_problem_ids',
            field=models.CharField(max_length=200, null=True, verbose_name='改错题列表id列表'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='tiankong_problem_ids',
            field=models.CharField(max_length=200, null=True, verbose_name='填空题列表id列表'),
        ),
    ]
