# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='work_kind',
            field=models.CharField(default='作业', max_length=20, verbose_name='作业类型'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='summary',
            field=models.TextField(null=True, verbose_name='实验小结'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='teacher_comment',
            field=models.TextField(null=True, verbose_name='教师评语'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='work_kind',
            field=models.CharField(default='作业', max_length=20, verbose_name='作业类型'),
        ),
    ]
