# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20170905_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='gaicuo_problem_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='tiankong_problem_info',
            field=models.TextField(null=True),
        ),
    ]
