# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20170906_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhomework',
            name='gaicuo_problem_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='tiankong_problem_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
