# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_myhomework_allow_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='allow_random',
            field=models.BooleanField(default=True, verbose_name='是否打乱选择题选项顺序>？'),
        ),
        migrations.AddField(
            model_name='homework',
            name='resubmit_number',
            field=models.IntegerField(default=100, verbose_name='提交次数限制'),
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='remained_number',
            field=models.IntegerField(default=0, verbose_name='提交次数限制'),
        ),
        migrations.AddField(
            model_name='myhomework',
            name='resubmit_number',
            field=models.IntegerField(default=100, verbose_name='提交次数限制'),
        ),
    ]
