# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20190705_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='show_answer',
            field=models.BooleanField(default=True, verbose_name='答案显示时机'),
        ),
    ]
