# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_homework_show_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhomework',
            name='show_answer',
            field=models.BooleanField(default=True, verbose_name='答案显示时机'),
        ),
    ]
