# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_myhomework_show_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='show_answer',
            field=models.CharField(default='每次提交后', max_length=20, verbose_name='何时显示答案'),
        ),
        migrations.AlterField(
            model_name='myhomework',
            name='show_answer',
            field=models.CharField(default='每次提交后', max_length=20, verbose_name='何时显示答案'),
        ),
    ]
