# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('ip', models.CharField(max_length=25, verbose_name='用户ip地址')),
                ('uid', models.PositiveIntegerField(verbose_name='用户id')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='上传文件大小')),
            ],
        ),
    ]
