# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-11 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.PositiveIntegerField(verbose_name='消息发送者')),
                ('receiver', models.PositiveIntegerField(verbose_name='消息接收者')),
                ('message', models.CharField(blank=True, max_length=512, verbose_name='消息')),
                ('questionId', models.PositiveIntegerField(blank=True, null=True)),
                ('isread', models.BooleanField(default=False, verbose_name='是否读过')),
            ],
        ),
    ]
