# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messagetype',
            field=models.PositiveSmallIntegerField(choices=[(0, '系统消息'), (1, '邀请消息'), (2, '关注消息'), (3, '问题状态消息')], default=0, verbose_name='消息类型'),
        ),
    ]
