# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_messagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='isread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messagetype',
        ),
        migrations.RemoveField(
            model_name='message',
            name='questionId',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
