# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20180412_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='collect_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='消息发布时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='rid',
            field=models.PositiveIntegerField(default=1, verbose_name='接收者id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sid',
            field=models.PositiveIntegerField(default=1, verbose_name='发送者id'),
        ),
    ]
