# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_message_rname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='collect_date',
            new_name='date',
        ),
    ]
