# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-14 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20180412_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messagetype',
            field=models.PositiveSmallIntegerField(choices=[(0, '系统消息'), (1, '邀请消息'), (2, '关注消息'), (3, '回答问题消息'), (4, '评论问题消息')], default=0, verbose_name='消息类型'),
        ),
    ]
