# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20180416_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='objtype',
            field=models.PositiveSmallIntegerField(choices=[(0, '问题的id'), (1, '答案的id')], default=0, verbose_name='对象类型'),
        ),
    ]
