# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20190418_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sname',
        ),
        migrations.AlterField(
            model_name='message',
            name='rid',
            field=models.PositiveIntegerField(verbose_name='接收者id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sid',
            field=models.PositiveIntegerField(verbose_name='发送者id'),
        ),
    ]
